# Generated by Django 6.0.6 on 2026-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('max_temp', models.FloatField(blank=True, null=True, verbose_name='最高温度(℃)')),
                ('min_temp', models.FloatField(blank=True, null=True, verbose_name='最低温度(℃)')),
                ('weather_desc', models.CharField(blank=True, max_length=50, verbose_name='天气状况')),
                ('wind_direction', models.CharField(blank=True, max_length=50, verbose_name='风向')),
                ('wind_level', models.CharField(blank=True, max_length=20, verbose_name='风力')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '天气数据',
                'verbose_name_plural': '天气数据',
                'db_table': 'weather_data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('avg_max_temp', models.FloatField(blank=True, null=True, verbose_name='月均最高温')),
                ('avg_min_temp', models.FloatField(blank=True, null=True, verbose_name='月均最低温')),
                ('max_temp_record', models.FloatField(blank=True, null=True, verbose_name='月最高温记录')),
                ('min_temp_record', models.FloatField(blank=True, null=True, verbose_name='月最低温记录')),
                ('rainy_days', models.IntegerField(default=0, verbose_name='降雨天数')),
                ('avg_humidity', models.FloatField(blank=True, null=True, verbose_name='平均湿度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '月度统计',
                'verbose_name_plural': '月度统计',
                'db_table': 'monthly_stats',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
