# Generated by Django 6.0.6 on 2026-06-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='格式：YYYY-MM', max_length=7, unique=True, verbose_name='月份')),
                ('advice_text', models.TextField(blank=True, verbose_name='建议文本')),
                ('tags', models.JSONField(blank=True, default=list, help_text='示例：["薄外套", "雨具"]', verbose_name='推荐标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '穿衣建议',
                'verbose_name_plural': '穿衣建议',
                'db_table': 'clothing_advice',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('records_count', models.IntegerField(default=0, verbose_name='抓取条数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'db_table': 'crawl_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='air_quality_score',
            field=models.IntegerField(blank=True, help_text='0-100，越高越好', null=True, verbose_name='空气质量'),
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='humidity_comfort_score',
            field=models.IntegerField(blank=True, help_text='0-100，越高越适宜', null=True, verbose_name='湿度适宜度'),
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='precipitation_score',
            field=models.IntegerField(blank=True, help_text='0-100，越适中越高', null=True, verbose_name='降水适中度'),
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='sunlight_score',
            field=models.IntegerField(blank=True, help_text='0-100，越高越充足', null=True, verbose_name='日照充足度'),
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='temp_comfort_score',
            field=models.IntegerField(blank=True, help_text='0-100，越高越舒适', null=True, verbose_name='温度舒适度'),
        ),
        migrations.AddField(
            model_name='monthlystats',
            name='weather_distribution',
            field=models.JSONField(blank=True, default=dict, verbose_name='天气分布'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_type',
            field=models.CharField(blank=True, choices=[('sunny', '晴天'), ('cloudy', '多云'), ('overcast', '阴天'), ('rainy', '雨天'), ('snowy', '雪天'), ('foggy', '雾/霾')], db_index=True, max_length=20, verbose_name='天气类型'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateField(unique=True, verbose_name='日期'),
        ),
    ]
