# Generated by Django 6.0.1 on 2026-06-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clothingadvice_crawltask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('day_temp', models.IntegerField(blank=True, null=True, verbose_name='白天气温(℃)')),
                ('night_temp', models.IntegerField(blank=True, null=True, verbose_name='夜间气温(℃)')),
                ('weather_desc', models.CharField(blank=True, max_length=50, verbose_name='天气状况')),
                ('week', models.CharField(blank=True, max_length=10, verbose_name='星期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '预报数据',
                'verbose_name_plural': '预报数据',
                'db_table': 'forecast_data',
                'ordering': ['date'],
            },
        ),
    ]
