# Generated by Django 6.0.1 on 2026-06-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_forecast_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingadvice',
            name='advice_categories',
            field=models.JSONField(blank=True, default=dict, help_text='{"clothing": {...}, "travel": {...}, "exercise": {...}, "health": {...}, "alert": {...}}', verbose_name='建议分类'),
        ),
        migrations.AlterField(
            model_name='clothingadvice',
            name='advice_text',
            field=models.TextField(blank=True, verbose_name='主要建议'),
        ),
    ]
